In [4]:
# Tạo array 2D (4x3) với các số từ 1 đến 12
# Tính tổng mỗi hàng và mỗi cột
# Tìm phần tử lớn nhất và vị trí của nó

import numpy as np
import random
array_2D = np.random.randint(0,12,size=(4,3))
print(array_2D)
# Tính tổng mỗi hàng
row_sums = np.sum(array_2D, axis=1)
print("Tổng mỗi hàng:", row_sums)
# Tính tổng mỗi cột
col_sums = np.sum(array_2D, axis=0)
print("Tổng mỗi cột:", col_sums)
# Tìm phần tử lớn nhất và vị trí của nó
max_value = np.max(array_2D)
max_position = np.unravel_index(np.argmax(array_2D), array_2D.shape)
print("Phần tử lớn nhất:", max_value)
print("Vị trí của phần tử lớn nhất:", max_position)

[[11 11  7]
 [ 4  8  3]
 [ 4  6  1]
 [ 2  7  8]]
Tổng mỗi hàng: [29 15 11 17]
Tổng mỗi cột: [21 32 19]
Phần tử lớn nhất: 11
Vị trí của phần tử lớn nhất: (0, 0)


In [8]:
# Cho dữ liệu nhiệt độ 7 ngày trong tuần (độ C)
temperatures = np.array([25.5, 27.2, 23.8, 29.1, 26.7, 24.3, 28.0])

# Yêu cầu:
# 1. Tính nhiệt độ trung bình
mean_temp = np.mean(temperatures)
print("Nhiệt độ trung bình là:", mean_temp.round(2))
# 2. Tìm ngày nóng nhất và lạnh nhất
max_temp = np.max(temperatures)
min_temp = np.min(temperatures)
print("Ngày nóng nhất:", max_temp)
print("Ngày lạnh nhất:", min_temp)

# 3. Đếm số ngày nhiệt độ > 26°C
hot_days = np.sum(temperatures > 26)
print("Số ngày nóng > 26°C:", hot_days)
# 4. Chuyển đổi sang độ F (F = C * 9/5 + 32)
temperatures_F = temperatures * 9/5 + 32
print("Nhiệt độ (°F):", temperatures_F)

Nhiệt độ trung bình là: 26.37
Ngày nóng nhất: 29.1
Ngày lạnh nhất: 23.8
Số ngày nóng > 26°C: 4
Nhiệt độ (°F): [77.9  80.96 74.84 84.38 80.06 75.74 82.4 ]
